### ISSUE TITLE
CamelCase column names in error messages?

### ISSUE THREAD

**Issue by hooverlunch** [vprokopchuk256/mv-mysql#5]
Love this gem!

Wondering though why the column names get camel cased in the error messages. Is there a reason?

**Comment by vprokopchuk256** [comment]
@hooverlunch - looks like a bug. Will take care of it nearest time.

**Comment by vprokopchuk256** [comment]
Fixed: https://github.com/vprokopchuk256/mv-mysql/releases/tag/v2.2.4
