### ISSUE TITLE
Using SIGNAL for error messages?

### ISSUE THREAD

**Issue by hooverlunch** [vprokopchuk256/mv-mysql#6]
As of 5.5, MySQL allows user defined errors via SIGNAL statement. Any plans to use it? Would be slightly less cryptic than the missing table one.

**Comment by vprokopchuk256** [comment]
@hooverlunch  - good suggestion. Would be implemented soon. Thank you!

**Comment by vprokopchuk256** [comment]
Fixed: https://github.com/vprokopchuk256/mv-mysql/releases/tag/v2.2.4

**Comment by hooverlunch** [comment]
Thanks!
