### ISSUE TITLE
DB schema spacing?

### ISSUE THREAD

**Issue by hooverlunch** [vprokopchuk256/mv-mysql#7]
I am using the `fix-db-schema-conflicts` to tidy my schema. This gem seems to introduce some formatting changes to the full schema. Like this:

```
-    t.string "medium", limit: 255
-    t.integer "mission_id", limit: 4
-    t.text "send_errors", limit: 65535
-    t.string "subject", limit: 255
+    t.string   "medium", limit: 255
+    t.integer  "mission_id", limit: 4
+    t.text     "send_errors", limit: 65535
+    t.string   "subject", limit: 255
```

I wonder why this is?

I can't really use this gem unless I can fix this somehow. Thoughts?

**Comment by vprokopchuk256** [comment]
@hooverlunch  - I've installed ```fix-db-schema-conflicts``` and everything was fine for me. I've just migrated db first that fixed that schema state. Not formatting changes after. Is this issue still reproducible for you?

**Comment by hooverlunch** [comment]
I will take a look when I get some time. Thanks.

**Comment by vprokopchuk256** [comment]
Closing this ticket because of the long period of inactivity.
